name: Build DocFX Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest #ubuntu-18.04 #windows-latest #windows-2019 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Build site
      #  run: docfx docfx.json
      # https://github.com/marketplace/actions/docfx-action
      - name: docfx-action
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docfx.json
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          #personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./_site
          #publish_branch: master  # default: gh-pages
